suma_api:
  myserver.example.com:
    username: apiuser
    password: gAAAAAACJFUep3aR1tKE6AqQELTcGqxNelq9pHgVg2P88YLvv33G7363LBgMhnJB8ut-RKzha0Uc8=

engines_dirs:
  - /srv/salt/engines

engines:
  - getsuma:
      interval: 300
